export const START_LOADING_INFO_PANEL = 'START_LOADING_INFO_PANEL';
export const START_LOADING_TASKS_PANEL = 'START_LOADING_TASKS_PANEL';
export const STOP_LOADING_INFO_PANEL = 'STOP_LOADING_INFO_PANEL';
export const STOP_LOADING_TASKS_PANEL = 'STOP_LOADING_TASK_PANEL';
