export const GET_CURRENT_NEWS = 'GET_CURRENT_NEWS';
export const GET_CURRENT_RATES = 'GET_CURRENT_RATES';
export const GET_CURRENT_WEATHER = 'GET_CURRENT_WEATHER';
export const GET_ERROR = 'GET_ERROR';
